version: '3'
services:
  nginx-app:
    container_name: workspace_container
    hostname: workspace_container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    depends_on:
      - node_container

  node_container:
    container_name: node_container
    image: node:latest
    working_dir: /usr/share/nginx/html
    volumes:
      - ./src:/usr/share/nginx/html
    # command: npm install
